services:
  microservicios-postgres14:
    container_name: microservicios-postgres14
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_springboot_cloud
      POSTGRES_PASSWORD: root
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - springcloud

  servicio-productos:
    container_name: servicio-productos
    image: georgegxx/servicio-productos:latest
    environment:
      DB_HOST: microservicios-postgres14:5432
      DB_DATABASE: db_springboot_cloud
      DB_USERNAME: postgres
      DB_PASSWORD: root
      # Usar la DNS de tu instancia EC2 de AWS
      CONFIG_SERVER_URL: ec2-44-200-117-39.compute-1.amazonaws.com:8888
      EUREKA_SERVER_URL: ec2-44-200-117-39.compute-1.amazonaws.com:8761
    networks:
      - springcloud
    depends_on:
      - microservicios-postgres14
    restart: unless-stopped

  servicio-items:
    container_name: servicio-items
    image: georgegxx/servicio-items:latest
    ports:
      - "8002:8002"
      - "8005:8005"
      - "8007:8007"
    networks:
      - springcloud
    depends_on:
      - servicio-productos
    restart: unless-stopped

volumes:
  data-postgres:

networks:
  springcloud: